name: NASA CI  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env : 
        CI :true
    strategy:
        matrix :
          node-version : [18.x , 20.x]
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version:  ${{matrix.node-version}}

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Build client
        run: npm run build
        run : npm run test
        working-directory: client
