name: NASA  CI  
on :
    push:
        branches: [master]
    pull_request: 
        branches : [master]
jobs:
    build:
        runs-on: ubuntu-latest 
        steps :
            - uses: actions/checkout@v1
            - name: Use Node.js version 20
              uses: actions/setup-node@v1
              with:
                    node-version: '20'
            - name: Install client dependencies
              run: npm install
              working-directory: ./client

            - name: Build client
              run: npm run build
              working-directory: ./client

      # Install and test server
            -  name: Install server dependencies
               run: npm install
               working-directory: ./server
     
